### ISSUE TITLE
ALS crashed while saving B&W image as JPEG on RPI4

### ISSUE THREAD

**Issue by deufrai** [gehelem/als#105]
```
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/opencv-L65chJ/opencv-3.2.0+dfsg/modules/imgproc/src/color.cpp, line 9716
Traceback (most recent call last):
  File "/home/pi/work/dev/als/src/als/code_utilities.py", line 33, in wrapped
    result = func(*args, **kwargs)
  File "/home/pi/work/dev/als/src/als/processing.py", line 445, in run
    self._handle_image(image)
  File "/home/pi/work/dev/als/src/als/code_utilities.py", line 33, in wrapped
    result = func(*args, **kwargs)
  File "/home/pi/work/dev/als/src/als/io/output.py", line 30, in _handle_image
    ImageSaver._save_image(image)
  File "/home/pi/work/dev/als/src/als/code_utilities.py", line 33, in wrapped
    result = func(*args, **kwargs)
  File "/home/pi/work/dev/als/src/als/io/output.py", line 50, in _save_image
    save_is_successful, failure_details = ImageSaver._save_image_as_jpg(image, target_path)
  File "/home/pi/work/dev/als/src/als/code_utilities.py", line 33, in wrapped
    result = func(*args, **kwargs)
  File "/home/pi/work/dev/als/src/als/io/output.py", line 136, in _save_image_as_jpg
    cv2.cvtColor(image.data, cv2.COLOR_RGB2BGR),
cv2.error: /build/opencv-L65chJ/opencv-3.2.0+dfsg/modules/imgproc/src/color.cpp:9716: error: (-215) scn == 3 || scn == 4 in function cvtColor
Abandon

```

**Comment by deufrai** [comment]
Fix tested OK
