### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by WirthmU** [gehelem/als#127]
I have tried to install ALS (from master) in Ubuntu 18.04. Setup fails with the following messages:

```
(venv) uw@uw-SBC-FITPC2:~/als$ python setup.py develop
Compiling UI files
Executing command : pyuic5 /home/uw/als/src/als/ui/save_wait_ui.ui -o /home/uw/als/src/generated/save_wait_ui.py --import-from=generated
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    compile_ui_and_rc.main()
  File "/home/uw/als/utils/compile_ui_and_rc.py", line 19, in main
    completed_process = subprocess.run([command, ] + args.split(" "))
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyuic5': 'pyuic5'
```

Any help to this?

**Comment by deufrai** [comment]
Hi,
Sorry for this
On a Debian / Ubuntu system, the `pyuic5` command is provided by the `pyqt5-dev-tools` package

Let us know if you succeed installing & using it

Clear skies

**Comment by WirthmU** [comment]
This did the trick - after installing the pyqt5 package the setup was successful.

However, when I run als I get the following error message:

bash: /usr/bin/als: No such file or directory

**Comment by deufrai** [comment]
Hi

Is the venv still active when you call `als` ?

**Comment by WirthmU** [comment]
Yes:

```
(venv) uw@uw-SBC-FITPC2:~$ als
bash: /usr/bin/als: No such file or directory
```

**Comment by deufrai** [comment]
hi
What is the result of the following command ? :
`which als`

expected result according to your setup :
`/home/uw/als/venv/bin/als`

**Comment by WirthmU** [comment]
As expected:
```
(venv) uw@uw-SBC-FITPC2:~$ which als
/home/uw/als/venv/bin/als
```

**Comment by WirthmU** [comment]
I did  a bit more of testing.
sudo reboot
cd als  (and not ALS_HOME as mentioned in GitHub)
source ./venv/bin/activate
als

```
Now I get the following error:
Traceback (most recent call last):
  File "/home/uw/als/venv/bin/als", line 11, in <module>
    load_entry_point('als', 'console_scripts', 'als')()
  File "/home/uw/als/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/uw/als/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/uw/als/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/uw/als/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/uw/als/src/als/main.py", line 9, in <module>
    from PyQt5.QtWidgets import QApplication
ModuleNotFoundError: No module named 'PyQt5'
```
I have tried to install the PyQt5 module using _pip3 install PyQt5_ but no success

**Comment by deufrai** [comment]
What hardware platform are you running this Ubuntu on ?
If it is a 64bits Intel or AMD CPU, you'd have better luck using our nightly builds (Don't be afraid, the last ones are very stable, as we are very close to the next release)
Just head to https://als-app.org/nightlies/ and get the latest one for your system

**Comment by WirthmU** [comment]
Here is the system information:
Processor:   Intel(R) Atom(TM) CPU Z550   @ 2.00G
Architecture:        i686
CPU op-mode(s):      32-bit

**Comment by deufrai** [comment]
So I suggest you switch to the 'develop' branch and paste the full output of the 'pip install -r requirements.txt' command. After having activated the venv. We might have missed something there

**Comment by WirthmU** [comment]
This is the output:
```
(venv) uw@uw-SBC-FITPC2:~/als$ pip install -r requirements.txt
Collecting astroalign==1.0.4
  Using cached astroalign-1.0.4-py2.py3-none-any.whl (9.0 kB)
Collecting astropy==4.0.1.post1
  Using cached astropy-4.0.1.post1-cp36-cp36m-manylinux1_i686.whl (6.4 MB)
Collecting dtcwt==0.12.0
  Using cached dtcwt-0.12.0.tar.gz (70 kB)
Requirement already satisfied: numpy==1.16.4 in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (1.16.4)
Collecting opencv-python-headless==4.1.0.25
  Using cached opencv_python_headless-4.1.0.25-cp36-cp36m-manylinux1_i686.whl (20.2 MB)
ERROR: Could not find a version that satisfies the requirement PyQt5==5.13.0 (from -r requirements.txt (line 6)) (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0)
ERROR: No matching distribution found for PyQt5==5.13.0 (from -r requirements.txt (line 6))
```

**Comment by deufrai** [comment]
Looks familiar
What python version are you using ?

**Comment by WirthmU** [comment]
python3

**Comment by deufrai** [comment]
Hi and sorry for the late reply

pyqt5 is not available from PyPi repo for 32 bits linux. But there is a way :

1) install python-Qt bindings system-wide with the following command : `sudo apt install python3-pyqt5`
2) create the venv with the folloing command : `python3 -m venv --system-site-packages venv`
3) remove line N°6 from requirements.txt
4) install requirements with the following command : `pip install -I -r requirements.txt`

**Comment by WirthmU** [comment]
I did as you suggested and it worked until I tried to install:
```
(venv) uw@uw-SBC-FITPC2:~/als$ pip install -I -r requirements.txt
Collecting astroalign==1.0.4
  Using cached astroalign-1.0.4-py2.py3-none-any.whl (9.0 kB)
Collecting astropy==4.0.1.post1
  Using cached astropy-4.0.1.post1-cp36-cp36m-manylinux1_i686.whl (6.4 MB)
Collecting dtcwt==0.12.0
  Using cached dtcwt-0.12.0.tar.gz (70 kB)
Collecting numpy==1.16.4
  Using cached numpy-1.16.4-cp36-cp36m-manylinux1_i686.whl (14.8 MB)
Collecting opencv-python-headless==4.1.0.25
  Using cached opencv_python_headless-4.1.0.25-cp36-cp36m-manylinux1_i686.whl (20.2 MB)
Collecting pywi==0.3.dev12
  Downloading pywi-0.3.dev12.tar.gz (520 kB)
     |████████████████████████████████| 520 kB 1.3 MB/s 
Collecting qimage2ndarray==1.8
  Downloading qimage2ndarray-1.8.tar.gz (183 kB)
     |████████████████████████████████| 183 kB 3.6 MB/s 
Collecting rawpy==0.13.1
  Downloading rawpy-0.13.1.tar.gz (116 kB)
     |████████████████████████████████| 116 kB 2.6 MB/s 
Collecting watchdog==0.9.0
  Downloading watchdog-0.9.0.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 527 kB/s 
Collecting pylint==2.3.1
  Downloading pylint-2.3.1-py3-none-any.whl (765 kB)
     |████████████████████████████████| 765 kB 2.7 MB/s 
Collecting Sphinx==2.2.0
  Downloading Sphinx-2.2.0-py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.2 MB/s 
Collecting pytest==5.1.2
  Downloading pytest-5.1.2-py3-none-any.whl (224 kB)
     |████████████████████████████████| 224 kB 2.4 MB/s 
Collecting pytest-cov==2.7.1
  Downloading pytest_cov-2.7.1-py2.py3-none-any.whl (17 kB)
Collecting coverage==4.5.4
  Downloading coverage-4.5.4-cp36-cp36m-manylinux1_i686.whl (202 kB)
     |████████████████████████████████| 202 kB 2.9 MB/s 
Collecting numba==0.45.1
  Downloading numba-0.45.1-cp36-cp36m-manylinux1_i686.whl (3.4 MB)
     |████████████████████████████████| 3.4 MB 238 kB/s 
Collecting sphinx-rtd-theme==0.4.3
  Downloading sphinx_rtd_theme-0.4.3-py2.py3-none-any.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 4.7 MB/s 
Collecting psutil==5.6.6
  Downloading psutil-5.6.6.tar.gz (447 kB)
     |████████████████████████████████| 447 kB 2.5 MB/s 
Collecting PyInstaller==3.6
  Downloading PyInstaller-3.6.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 366 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/uw/als/venv/bin/python3 /home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp8sjtw_tj
       cwd: /tmp/pip-install-z6339jg0/PyInstaller
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 99, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/uw/als/venv/bin/python3 /home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp8sjtw_tj Check the logs for full command output.
```

**Comment by deufrai** [comment]
You can skip Pyinstaller. Just remove the line `PyInstaller==3.6` in requirements.txt and relaunch
We'll get there, eventually

**Comment by WirthmU** [comment]
It looks that there is a bit more installation going on but then:

```
....
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 1.7 MB/s 
Collecting lazy-object-proxy==1.4.*
  Using cached lazy-object-proxy-1.4.3.tar.gz (34 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/uw/als/venv/bin/python3 /home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkwsplc7u
       cwd: /tmp/pip-install-bvijlgpr/lazy-object-proxy
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 99, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/uw/als/venv/bin/python3 /home/uw/als/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkwsplc7u Check the logs for full command output.
```

**Comment by deufrai** [comment]
bumped into that one myself when debugging installation on another 'strange' system

please use `pip --no-use-pep517 install -I -r requirements.txt` 

Did the trick for me

Thanks for your patience ...

**Comment by WirthmU** [comment]
The command should be: `pip install --no-use-pep51 -I -r requirements.txt`

Still errors:

```
Installing collected packages: numpy, scipy, Pillow, imageio, kiwisolver, six, python-dateutil, cycler, pyparsing, matplotlib, decorator, networkx, PyWavelets, scikit-image, sep, astroalign, astropy, dtcwt, opencv-python-headless, pytz, pandas, pywi, qimage2ndarray, rawpy, PyYAML, argh, pathtools, watchdog, mccabe, typed-ast, wrapt, lazy-object-proxy, astroid, isort, pylint, babel, sphinxcontrib-qthelp, idna, urllib3, chardet, certifi, requests, alabaster, packaging, snowballstemmer, sphinxcontrib-htmlhelp, MarkupSafe, Jinja2, imagesize, sphinxcontrib-jsmath, sphinxcontrib-serializinghtml, sphinxcontrib-devhelp, setuptools, docutils, sphinxcontrib-applehelp, Pygments, Sphinx, more-itertools, wcwidth, zipp, importlib-metadata, atomicwrites, attrs, pluggy, py, pytest, coverage, pytest-cov, llvmlite, numba, sphinx-rtd-theme, psutil
    Running setup.py install for rawpy ... error
    ERROR: Command errored out with exit status 1:
     command: /home/uw/als/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-brffbog_/rawpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-brffbog_/rawpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gjgnl6st/install-record.txt --single-version-externally-managed --compile --install-headers /home/uw/als/venv/include/site/python3.6/rawpy
         cwd: /tmp/pip-install-brffbog_/rawpy/
    Complete output (47 lines):
    Package libraw was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libraw.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libraw' found
    Package libraw was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libraw.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libraw' found
    Package libraw was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libraw.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libraw' found
    Package libraw was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libraw.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libraw' found
    Package libraw was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libraw.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libraw' found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-3.6
    creating build/lib.linux-i686-3.6/rawpy
    copying rawpy/_version.py -> build/lib.linux-i686-3.6/rawpy
    copying rawpy/enhance.py -> build/lib.linux-i686-3.6/rawpy
    copying rawpy/__init__.py -> build/lib.linux-i686-3.6/rawpy
    running build_ext
    building 'rawpy._rawpy' extension
    creating build/temp.linux-i686-3.6
    creating build/temp.linux-i686-3.6/rawpy
    i686-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_HAS_LIBRAW_CONFIG_H=0 -I/home/uw/als/venv/lib/python3.6/site-packages/numpy/core/include -I/home/uw/als/venv/include -I/usr/include/python3.6m -c rawpy/_rawpy.cpp -o build/temp.linux-i686-3.6/rawpy/_rawpy.o
    In file included from /home/uw/als/venv/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                     from /home/uw/als/venv/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /home/uw/als/venv/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from rawpy/_rawpy.cpp:663:
    /home/uw/als/venv/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    In file included from rawpy/_rawpy.cpp:665:0:
    rawpy/def_helper.h:1:10: fatal error: libraw_version.h: No such file or directory
     #include "libraw_version.h"
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'i686-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/uw/als/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-brffbog_/rawpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-brffbog_/rawpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gjgnl6st/install-record.txt --single-version-externally-managed --compile --install-headers /home/uw/als/venv/include/site/python3.6/rawpy Check the logs for full command output.
```

**Comment by deufrai** [comment]
yes again, you need libraw installed on your system, now

`sudo apt install libraw-dev libraw-bin`

I'm sorry for that many exchanges. But it looks like many binary wheels are missing for 32 bit linux systems.
Some other errors are exptected, I'll guide you as they occur

**Comment by WirthmU** [comment]
Getting close to it!

I get some errors but I am not sure if they are important:
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

rms 0.1 requires imreg_dft, which is not installed.
launchpadlib 1.10.6 requires testresources, which is not installed.
rms 0.1 requires cython>=0.27.3, but you'll have cython 0.26.1 which is incompatible.
rms 0.1 requires imageio==2.6.1, but you'll have imageio 2.9.0 which is incompatible.
paramiko 2.7.1 requires cryptography>=2.5, but you'll have cryptography 2.1.4 which is incompatible.
```
Its good that now I can start ALS and I get the opening screen with the settings. This is what I see in the terminal window:
```
2020-07-30 14:36:58,727 MainThread   als.ui.windows       INFO     First run detected
QXcbConnection: XCB error: 148 (Unknown), sequence: 172, resource id: 0, major code: 140 (Unknown), minor code: 20
```

**Comment by deufrai** [comment]
I'm quite confident you can get away with those last errors.
But python being an interpreted language, you'll have to actually use all the features to make sure installation is correct.

Anyway, thanks for the reports and congrats on the successful first run

Truly hope you first real live stacking goes smoothly

We'll be there to assist in case of troube

**Comment by WirthmU** [comment]
How would I change the settings from the Windows menu?

**Comment by deufrai** [comment]
From the main menu : Edit > Preferences
Only accessible when session *and* web server are stopped

**Comment by WirthmU** [comment]
I can see the Main controls, Processing, Session log and the Camera tile. No Edit>Preferences (even with Session and Image server stopped)

**Comment by deufrai** [comment]
can't you see the main menu at the top ?

![image](https://user-images.githubusercontent.com/1608988/88941497-5e242100-d289-11ea-816d-1ca45acebaa5.png)

**Comment by WirthmU** [comment]
I found it - it looks a bit different in Ubuntu.

Now I need to find a way to safe my pictures into raw instead of jpeg - or transform them into raw or fits format

**Comment by deufrai** [comment]
If you need lossless save format, go to preferences and pick PNG or TIFF
FITS saving may come in a future version

**Comment by deufrai** [comment]
Looks like installation is ok, right ?
Can we close this ticket ?

**Comment by WirthmU** [comment]
Thank you for your great support!
