### ISSUE TITLE
Nigthly builds don't work under Ubuntu 20.04.1, RPi et Windows 10

### ISSUE THREAD

**Issue by lyes91** [gehelem/als#133]
Bonjour,

Impossible de lancer als-0.7-dev-16931f0.run depuis mon PC sous ubuntu 20.04.1.
J'ai correctement récuperé l'archive, décompréssé, et rendu executable mais rien ne se passe lors du lancement.

J'ai tenté de lancer l'executable directement depuis un terminal. J'ai les messages d'erreurs ci-dessous :

lyes@Lyes-Portable:~/als$ uname -a
Linux Lyes-Portable 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
lyes@Lyes-Portable:~/als$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
lyes@Lyes-Portable:~/als$ ll
total 180776
drwxrwxr-x  2 lyes lyes      4096 oct.  29 13:36 ./
drwxr-xr-x 23 lyes lyes      4096 oct.  29 13:43 ../
-rwxrwxr-x  1 lyes lyes 185106296 oct.  29 13:36 als-0.7-dev-16931f0.run*
lyes@Lyes-Portable:~/als$ ./als-0.7-dev-16931f0.run 
Traceback (most recent call last):
  File "als/main.py", line 17, in <module>
  File "/stock/bamboo-agent/builder-01/xml-data/build-dir/ALS-DB-JOB1/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "als/logic.py", line 34, in <module>
  File "/stock/bamboo-agent/builder-01/xml-data/build-dir/ALS-DB-JOB1/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "als/io/output.py", line 18, in <module>
  File "/stock/bamboo-agent/builder-01/xml-data/build-dir/ALS-DB-JOB1/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "als/processing.py", line 12, in <module>
  File "/stock/bamboo-agent/builder-01/xml-data/build-dir/ALS-DB-JOB1/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "scipy/signal/__init__.py", line 307, in <module>
  File "/stock/bamboo-agent/builder-01/xml-data/build-dir/ALS-DB-JOB1/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "scipy/signal/_peak_finding.py", line 8, in <module>
  File "/stock/bamboo-agent/builder-01/xml-data/build-dir/ALS-DB-JOB1/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "scipy/stats/__init__.py", line 388, in <module>
  File "/stock/bamboo-agent/builder-01/xml-data/build-dir/ALS-DB-JOB1/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "scipy/stats/stats.py", line 180, in <module>
  File "/stock/bamboo-agent/builder-01/xml-data/build-dir/ALS-DB-JOB1/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "scipy/stats/distributions.py", line 11, in <module>
  File "/stock/bamboo-agent/builder-01/xml-data/build-dir/ALS-DB-JOB1/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "scipy/stats/_continuous_distns.py", line 21, in <module>
  File "_stats.pyx", line 1, in init scipy.stats._stats
ModuleNotFoundError: No module named 'scipy.special.cython_special'
[3861] Failed to execute script main

Avez-vous une idée ?
Merci

**Comment by deufrai** [comment]
Hi and thanks for the report

I'll try and reproduce the issue

If confirmed, working builds will be published in nightlies ASAP

**Comment by lyes91** [comment]
Hi,
I just tried to run the versions for raspberry and windows. None of them work. My tests took place under windows 10 (fatal error) and raspberry pi 4 under raspbian (same error as for Ubuntu).

**Comment by deufrai** [comment]
Hi

published nightly build has just been replaced with the last working one.
You can grab it from the usual place : https://als-app.org/nightlies/

This is just a workaround for now.

A working build for commit 16931f08 will be published in an unforeseen future

Thanks for your patience

**Comment by deufrai** [comment]
Hi again
nightly builds have been fixed and latest published build tested on all platforms : OK

Have fun & clear skies
