### ISSUE TITLE
Cannot install ALS on Pi4 running astroberry

### ISSUE THREAD

**Issue by ellmer51** [gehelem/als#152]
I am installing ALS on a raspberry Pi 4 4gb running astroberry.  When I type in the command:
$ ./utils/venv_setup.sh
Everything looks good and at the end I get this in red:
ERROR: Could not find a version that satisfies the requirement PyQt5==5.13.0 (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6)
ERROR: No matching distribution found for PyQt5==5.13.0
Then as I go through the install process, after I type in the command:
$ python setup.py develop
I get this:
Compiling UI files
==================
Executing command : pyuic5 /home/astroberry/als/src/als/ui/about_ui.ui -o /home/astroberry/als/src/generated/about_ui.py --import-from=generated
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    compile_ui_and_rc.main()
  File "/home/astroberry/als/utils/compile_ui_and_rc.py", line 19, in main
    completed_process = subprocess.run([command, ] + args.split(" "))
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyuic5': 'pyuic5'
And when I try to launch ALS, I type:
$ ALS
and it returns:
bash: als: command not found
I tried installing from <master> and <release/0.7> with the same results.

**Comment by ellmer51** [comment]
I ended up installing a nightly release and it worked fine.
