### ISSUE TITLE
Crash on startup when trying to kill zombie processes

### ISSUE THREAD

**Issue by deufrai** [gehelem/als#92]
Occurs on develop branch (commit 40ccd0c)

```
Traceback (most recent call last):
  File "/Users/cliffs/als/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 356, in catch_zombie
    yield
  File "/Users/cliffs/als/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 422, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cliffs/als/venv/bin/als", line 11, in <module>
    load_entry_point('als', 'console_scripts', 'als')()
  File "/Users/cliffs/als/src/als/main.py", line 35, in main
    if process.name() == "Stacker":
  File "/Users/cliffs/als/venv/lib/python3.7/site-packages/psutil/__init__.py", line 738, in name
    cmdline = self.cmdline()
  File "/Users/cliffs/als/venv/lib/python3.7/site-packages/psutil/__init__.py", line 791, in cmdline
    return self._proc.cmdline()
  File "/Users/cliffs/als/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 338, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/cliffs/als/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 422, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/cliffs/als/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 367, in catch_zombie
    raise ZombieProcess(proc.pid, proc._name, proc._ppid)
psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=63124)
```

**Comment by deufrai** [comment]
Fixed
